Merge develop in main - Stichwortsuche
mi-classroom/mi-web-technologien-beiboot-ss2021-JanKoll pull request #6
Opened 2021-05-27 15:46 UTC by JanKoll

2021-05-29 13:27 UTC, Narua2010 requested changes
Nach dem ersten Build bekomme ich jedes mal den folgenden Fehler, wenn ich den Ordner auswähle? Nachdem ich aktualisiere ist dieser jedoch auf weg? Keine Ahnung ob ich villt. einfach zu schnell geklickt habe und noch nicht alles geladen war?

![image](https://user-images.githubusercontent.com/34771575/120071974-c605ec80-c091-11eb-852c-3be7266abcf0.png)

Das Suchfeld ist zwar vorhanden, jedoch funktioniert noch nichts? Ggf. nicht richtig implementiert? Würde in dem Fall jedoch erst einen PR stellen, wenn die Funktionen soweit vorhanden sind, damit umgeht man Verwirrung :) 

Darüber hinaus empfehle ich das selbe was mir Benedikt empfohlen hatte, mach ein zusätzlichen Suchbutton bzw. Interaktionselement bei der Suche hinzu, sodass der User weiß wie es weiter geht. 

Ansonsten finde ich deine Dokumentation echt richtig gut, und auch der Strukturelle Aufbaue gefällt mir sehr - sollte villt. doch mehr mit Vue machen anstatt Angular 👍

2021-05-29 13:27 UTC, Narua2010 commented on README.md
> +`--build` wird nurbenötigt, wenn Änderungen am Code vorgenommen wurden. Um die Container wieder zu zerstören, muss der Befehl `docker-compose down` ausgeführt werden.
du hast hier einen Encode Fehler :) (nur?benötigt)

2021-05-29 13:27 UTC, Narua2010 commented on client/src/components/Home.vue
> +      <input type="text" placeholder="Serach" v-model="search" v-on:keyup.enter="getSearch(search)" />
Typo Fehler (placeholder="Search")

2021-05-29 15:35 UTC, BenediktEngel commented
> Nach dem ersten Build bekomme ich jedes mal den folgenden Fehler, wenn ich den Ordner auswähle? Nachdem ich aktualisiere ist dieser jedoch auf weg? Keine Ahnung ob ich villt. einfach zu schnell geklickt habe und noch nicht alles geladen war?
Bei mir tritt der gleiche fehler auf, und der nodejs container stürtzt ab. 
<img width="644" alt="Bildschirmfoto 2021-05-29 um 17 27 33" src="https://user-images.githubusercontent.com/32795896/120075859-3ec17480-c0a3-11eb-8a1d-ddeb1e063be5.png">
aber ich verstehe leider nicht woran das liegt, im code finde ich diesbezüglich nämlich keinen fehler...
Also irgendwas hakt glaub beim server, anzeige der ordner funktioniert nur sobald ich einen auswählen will oder was in die suche eingebe stürtzt es ab...

2021-05-30 15:00 UTC, JanKoll commented on README.md
> +`--build` wird nurbenötigt, wenn Änderungen am Code vorgenommen wurden. Um die Container wieder zu zerstören, muss der Befehl `docker-compose down` ausgeführt werden.
fixed ✅

2021-05-30 15:00 UTC, JanKoll commented on client/src/components/Home.vue
> +      <input type="text" placeholder="Serach" v-model="search" v-on:keyup.enter="getSearch(search)" />
fixed ✅

2021-05-30 15:03 UTC, JanKoll commented
Danke für das Feedback! 👍 

Das Problem beim Initialen laden war, das die Variablen noch nicht gesetzt waren, die für die Anzeige der Bilder benötigt werden. Da checke ich jetzt erst, ob die undefined sind (trotzdem komischer Fehler, nach einem Reload funktioniert das ganze, auch Browser übergreifend...).

Bei der Suche hat der teilweise leere Elemente in das Array gelegt, die sortiere ich jetzt vorher aus.

2021-05-30 15:36 UTC, Narua2010 approved these changes
LGTM 👍

2021-05-30 18:55 UTC, BenediktEngel commented
Läuft bei mir leider noch nicht ganz, sobald ein bild angefordert wird stürtzt der Server nämlich wieder ab. maybe liegt es aber auch daran das der Port 3000 nicht richtig geleert und wieder freigegeben wird, weil meine dev-frontend läuft auch auf dem ich mach mal nen restart und schau es mir dann morgen nochmal an.

2021-05-31 07:41 UTC, BenediktEngel commented
Okay ja also das mit dem Port war natürlich quatsch.. weil die ordnerstruktur wurde ja zurück geschickt. Also wenn ich es lokal laufen lasse funktioniert es bei mir.. nur in docker nicht. aber vielleicht schauen wir da einfach mal nachher gemeinsam drüber @JanKoll aber ich schreib dir auch nochmal auf discord

2021-05-31 08:00 UTC, Narua2010 commented
> Okay ja also das mit dem Port war natürlich quatsch.. weil die ordnerstruktur wurde ja zurück geschickt. Also wenn ich es lokal laufen lasse funktioniert es bei mir.. nur in docker nicht. aber vielleicht schauen wir da einfach mal nachher gemeinsam drüber @JanKoll aber ich schreib dir auch nochmal auf discord

Wundert mich tatsächlich etwas, weil ich es im Docker ausgeführt hatte und alles einwandfrei lief?

2021-06-06 10:06 UTC, BenediktEngel approved these changes
Gebe jetzt ein Approve scheint ja nur ein Fehler in meiner Umgebung zu sein

2021-06-12 17:24 UTC, merged